spring.application.name=gateway_service
server.port=8089


# Point to your local Docker Redis container instance
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Main Routing Setup
spring.cloud.gateway.server.webflux.routes[0].id=job-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/jobs/**

# The Filter Properties (Corrected Webflux Namespacing)
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.replenishRate=1
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=3
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.redis-rate-limiter.requestedTokens=3
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}